### ISSUE TITLE
Modern Authentication for Unattended scripts without certificate based authentication

### ISSUE THREAD

**Issue by Usman-Majeed** [JustinGrote/ExchangeOnlineManagement#1]
Dear Team EXO V2,
I have an application which connects multiple tenants via windows services to perform day-to-day tasks in scheduled manners behind the scene. I want to know is there any possible way to connect to exchange online via 'AccessToken' parameter like it is done for Microsoft Graph Shell or Microsoft Teams ? If there not exists any then is there a plan for this functionality in future ?

As per research it is found that behind the scene, module is using Graph REST API and it works on OAuth2 and Token based authentication. So I assume that it will be easy to provide an overloaded function and/or cmdlet parameter in module to work with AccessTokens directly.

**Comment by JustinGrote** [comment]
@Usman-Majeed this is my own personal repository. This is not the Exchange Online management team's repository.
